### PR TITLE
Use LIB_INSTALL_DIR

### PR DESCRIPTION
**Pull request by drgraham**
Fedora uses `lib64`. This should work for either path.

### CODE REVIEW

**Comment by Kagetsuki** [comment]
@drgraham I somehow missed this! Please accept my apologies. I'll be checking later today.

Thank you for your interest and contribution!

**Comment by Kagetsuki** [comment]
@drgraham I took a look at this and discovered there is an issue with LIB_INSTALL_DIR and Debian based distros. Basically Debian doesn't follow the 32bit lib and 64bit lib64 separation "rule" - likely due to the fact Debian was the first distro that had a full 64bit rollout and they did that by literally building each package in-place as amd64. There's even a convention to put both 32bit and 64bit versions of the same package inside lib.

So essentially, while your fix is correct, it breaks Debian/Ubuntu/etc. builds. There must be a way to handle this - I'll dig around and see if I can have a branch for you to test by the end of the week.

**Comment by drgraham** [comment]
@Kagetsuki Ah, sorry. How about this, setting LIB_INSTALL_DIR if it is not? It still builds fine on Fedora, and gets it going again on Debian.

**Comment by Kagetsuki** [comment]
@drgraham I did just that! Can you do me a favour and checkout the upstream branch "adjust_build_config". I confirmed it's working on Ubuntu and Debian but I don't have a Fedora box handy. Will have @R-Y double check on OS-X tomorrow.

**Comment by drgraham** [comment]
@Kagetsuki Sure, no problem. The `adjust_build_config` branch does work properly on Fedora.

**Comment by Kagetsuki** [comment]
Sorry for the delay! Tested on pretty much everything and merged with master.

**Pull request closed without merging**
